server:
  run_mode: debug
  port: 8081
  jwt_secret_key: 123456

database:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  dbname: bcw_operator

redis:
  host: 127.0.0.1
  password: ""
  db: 0